### ISSUE TITLE
Port `PerCharacterEscaper`

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/selfie-python-wip#21]
- Take the next step in #7.

The goal is to implement this interface

https://github.com/diffplug/selfie-python-wip/blob/757e0fe534c831179c7dea75c7d503f480e7fd6c/jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/PerCharacterEscaper.kt#L23-L31

Using this code

https://github.com/diffplug/selfie-python-wip/blob/757e0fe534c831179c7dea75c7d503f480e7fd6c/jvm/selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/PerCharacterEscaper.jvm.kt#L18-L153

**Comment by Trickybrain** [comment]
Test Part of PerCharacterEscaper
https://github.com/diffplug/selfie-python-wip/blob/5e984657f4d14707bc09c5d8bb804059963b398c/jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/PerCharacterEscaperTest.kt#L25-L91
