### ISSUE TITLE
SnapshotValueReader

### ISSUE THREAD

**Issue by Trickybrain** [diffplug/selfie-python-wip#32]
To take step in https://github.com/diffplug/selfie-python-wip/issues/7

SnapshotValueReader Test

https://github.com/diffplug/selfie-python-wip/blob/2aededc364606e8dcd3c3f69669cb415a0b34b2f/jvm/selfie-lib/src/jvmTest/kotlin/com/diffplug/selfie/SnapshotValueReaderTest.kt#L22-L175

SnapshotValueReader

https://github.com/diffplug/selfie-python-wip/blob/2aededc364606e8dcd3c3f69669cb415a0b34b2f/jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SnapshotFile.kt#L283-L390

**Comment by nedtwigg** [comment]
Closed by #44
