### ISSUE TITLE
SnapshotReader

### ISSUE THREAD

**Issue by Trickybrain** [diffplug/selfie-python-wip#33]
To take step in https://github.com/diffplug/selfie-python-wip/issues/7

SnapshotReader Test

https://github.com/diffplug/selfie-python-wip/blob/2aededc364606e8dcd3c3f69669cb415a0b34b2f/jvm/selfie-lib/src/jvmTest/kotlin/com/diffplug/selfie/SnapshotReaderTest.kt#L21-L73

SnapshotReader

https://github.com/diffplug/selfie-python-wip/blob/2aededc364606e8dcd3c3f69669cb415a0b34b2f/jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SnapshotFile.kt#L243-L280

**Comment by nedtwigg** [comment]
- Closed by #48
