### ISSUE TITLE
LiteralString

### ISSUE THREAD

**Issue by SDelgado-21** [diffplug/selfie-python-wip#41]
From Epic: inline snapshot #8 
Implementation:
https://github.com/diffplug/selfie-python-wip/blob/a9c17e80d81b78989bcc516e53881b705f19566e/jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt#L113-L348
Test:
https://github.com/diffplug/selfie-python-wip/blob/a9c17e80d81b78989bcc516e53881b705f19566e/jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralStringTest.kt#L21-L102

**Comment by nedtwigg** [comment]
Note that Python strings are fairly different from Java and Kotlin. Should be a little bit easier than the Kotlin code, but it means that straight-up porting won't work as well.

**Comment by nedtwigg** [comment]
- Practically closed #47
